### ISSUE TITLE
Include example plugin that uses multiple data sources

### ISSUE THREAD

**Issue by CptanPanic** [IBM-IoT/node-red-contrib-graphs#1]
I just stumbled upon this plugin and it is what I need. But I would like to be able to create a graph that has more than one data source.  Firstly is this possible with this node, if so it would be great if it was included as an example, or at least some documentation on how to accomplish this.

**Comment by cristian-t** [comment]
Hi,

Yes, it is possible to have multiple datasources defined and have graphs use more than one datasource. To create multiple datasources, simply create multiple datasource nodes. The dashboard application will then list all datasources deployed in Node-RED. You can then configure any graph to use as many datasources as you want.

I'll add this to the documentation as soon as I can. Thanks for letting me know!

**Comment by cristian-t** [comment]
Oops, did not mean to do that.
I've added a new flow example to the documentation (605922c67cdf7c16691e36f25219cdd3ee1d69ca), showing 2 datasources.
Let me know if you need any more help.
