### ISSUE TITLE
Rows 21-23 in server.js prevent static content from loading

### ISSUE THREAD

**Issue by mikeS7** [IBM-IoT/node-red-contrib-graphs#2]
Code in lines 21-23 of server.js always returns index.html instead of requested content.

**Comment by cristian-t** [comment]
That should work as intended. First an express static route is set up, so existing static files are served correctly. The route at lines 21-23 is set up to allow serving index.html only if any of the previous routes are not satisfied. This allows me to use HTML5's pushState to create same-page navigation with routes like /dash/ (for main page) and /dash/board/0 (for accessing a certain dashboard), both those routes serving index.html.
Please let me know if you're experiencing any issues.

**Comment by mikeS7** [comment]
<img width="255" alt="screen shot 2015-09-09 at 20 52 20" src="https://cloud.githubusercontent.com/assets/9680581/9769765/c65e6fbc-5734-11e5-8609-9f7867d1e783.png">
what I've got

**Comment by cristian-t** [comment]
I see. I think I know what is happening. Could you tell me the address you are using to access this page? Feel free to omit host/ip and port, I'm only interested in the path.

**Comment by cristian-t** [comment]
I can't seem to be able to reproduce it, and I've tried it running Node.js 0.10 and 0.12, on different operating systems, and using IE, Firefox, and Chrome.
What about the other routes? Do http://host:port/dash/api/plugins or http://host:port/dash/api/user/settings give you index.html as well? Or is the static route the only one not working properly?

**Comment by mikeS7** [comment]
It's incompatibility with node-red-contrib-freeboard node, after removing all is working fine.
Will investigate more tomorrow

**Comment by cristian-t** [comment]
Oh, interesting, thank you for letting me know. I'll look into it as well. I'm sure there's a way to have them co-exist :)
