### ISSUE TITLE
plugin crashes node-red on startup

### ISSUE THREAD

**Issue by jwcrawley** [IBM-IoT/node-red-contrib-graphs#4]
Greetings,

I proceeded to install graphs globally on my machine. After the npm command finished, I started up node-red:

    josh@ThinkPad-T61:~$ node-red

    Welcome to Node-RED
    ===================

    22 Sep 07:00:39 - [info] Node-RED version: v0.11.1
    22 Sep 07:00:39 - [info] Node.js  version: v0.10.25
    22 Sep 07:00:39 - [info] Loading palette nodes
    22 Sep 07:00:40 - [info] Dashboard up and running
    22 Sep 07:00:40 - [warn] ------------------------------------------
    22 Sep 07:00:40 - [warn] Failed to register 1 node type
    22 Sep 07:00:40 - [warn] Run with -v for details
    22 Sep 07:00:40 - [warn] ------------------------------------------
    22 Sep 07:00:40 - [info] Settings file  : /usr/local/lib/node_modules/node-red/settings.js
    22 Sep 07:00:40 - [info] User directory : /home/josh/.node-red
    22 Sep 07:00:40 - [info] Flows file : /home/josh/.node-red/flows_ThinkPad-T61.json
    22 Sep 07:00:40 - [info] Server now running at http://127.0.0.1:1880/
    22 Sep 07:00:40 - [red] Uncaught Exception:
    22 Sep 07:00:40 - Error: EACCES, open '/usr/local/lib/node_modules/node-red-contrib-graphs/static/index.html'

I would like to be able to use this node, but unsure what is needed. I did try `touch`ing the files given errors on another machine, but lead to similar crashes.

Any help would be gladly taken :)

**Comment by cristian-t** [comment]
It looks like the user running Node-RED doesn't have read/write access to that location. Did you install `node-red-contrib-graphs` globally? (`npm install -g node-red-contrib-graphs`)

**Comment by reilly3000** [comment]
I'm having the same issue and did a global install

**Comment by cristian-t** [comment]
Right now, it's not a good idea to install this package globally since it requires write access to the location it was installed at.
