### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by jschuryk** [IBM-IoT/node-red-contrib-graphs#5]
I have loaded the node-red-contrib-graphs under my node-red install.

I imported the example flows from the github page.

When I start node-red, or redeploy changes I get an error in the debug window regarding the trim property.  In the log file, I see the same error: 

1 Oct 22:18:43 - [info] Node-RED version: v0.11.1
1 Oct 22:18:43 - [info] Node.js  version: v0.12.7
1 Oct 22:18:43 - [info] Loading palette nodes
1 Oct 22:18:48 - [info] Dashboard up and running
...
1 Oct 22:25:33 - [error] [iot-datasource:7e4d7f84.81b28] TypeError: Cannot read property 'trim' of undefined

Any ideas what is going on?

Thanks,

Jerry

**Comment by cristian-t** [comment]
The node is attempting to read a property that doesn't exist (because it was added in a later version). It's not backwards-compatible. The easiest way to fix it right now is to double-click the node, and hit "Ok" without changing anything. That will update its properties.

**Comment by cristian-t** [comment]
Closed due to inactivity.
